[project]
name = "propms"
authors = [
    { name = "Aakvatech", email = "info@aakvatech.com"}
]
description = "Property Management Solution"
requires-python = ">=3.10,<3.13"
dynamic = ["version"]
dependencies = [
    "frappe>=16.0.0"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
